{
  "artifacts": [],
  "command": "main_program",
  "experiment": {
    "base_dir": "D:\\User\\William\\Documents\\Devoir\\Projet Deep\\Projet_GLO7030\\code",
    "dependencies": [
      "numpy==1.15.0",
      "sacred==0.7.4"
    ],
    "mainfile": "main.py",
    "name": "Doodle_Boys",
    "repositories": [],
    "sources": [
      [
        "data_set_file.py",
        "_sources\\data_set_file_2225f8a61d29ddc77f5addb4ff7d494e.py"
      ],
      [
        "main.py",
        "_sources\\main_9d4181ca973859805992d664b5c9beb5.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sacred\\config\\captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"D:/User/William/Documents/Devoir/Projet Deep/Projet_GLO7030/code/main.py\", line 33, in main_program\n    data_valid=create_huge_data_set(path_data,nb_rows=99,size_image=size_image_train,skip_rows=nb_row_per_classe)\n",
    "  File \"D:\\User\\William\\Documents\\Devoir\\Projet Deep\\Projet_GLO7030\\code\\data_set_file.py\", line 123, in create_huge_data_set\n    doodles = ConcatDataset([DoodlesDataset(fn,path,nrows=nb_rows, size=size_image,skiprows=skip_rows) for fn in filenames])\n",
    "  File \"D:\\User\\William\\Documents\\Devoir\\Projet Deep\\Projet_GLO7030\\code\\data_set_file.py\", line 123, in <listcomp>\n    doodles = ConcatDataset([DoodlesDataset(fn,path,nrows=nb_rows, size=size_image,skiprows=skip_rows) for fn in filenames])\n",
    "  File \"D:\\User\\William\\Documents\\Devoir\\Projet Deep\\Projet_GLO7030\\code\\data_set_file.py\", line 60, in __init__\n    self.doodle = pd.read_csv(file, usecols=['drawing'], nrows=nrows, skiprows=skiprows) #Data set pandas\n",
    "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\", line 678, in parser_f\n    return _read(filepath_or_buffer, kwds)\n",
    "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\", line 440, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n",
    "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\", line 787, in __init__\n    self._make_engine(self.engine)\n",
    "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\", line 1014, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n",
    "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\", line 1749, in __init__\n    _validate_usecols_names(usecols, self.orig_names)\n",
    "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\", line 1134, in _validate_usecols_names\n    \"columns expected but not found: {missing}\".format(missing=missing)\n",
    "ValueError: Usecols do not match columns, columns expected but not found: ['drawing']\n"
  ],
  "heartbeat": "2019-03-30T13:58:33.069754",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz",
    "hostname": "DESKTOP-04C6VBJ",
    "os": [
      "Windows",
      "Windows-10-10.0.17763-SP0"
    ],
    "python_version": "3.7.1"
  },
  "meta": {
    "command": "main_program",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2019-03-30T13:58:32.940124",
  "status": "FAILED",
  "stop_time": "2019-03-30T13:58:33.092712"
}